FROM python:slim
LABEL authors="Or"


WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY Producer/mainProducer.py .
COPY Producer/Manager_Producer.py .
COPY DALs/Kafka.py .
COPY Models/Reader.py .
COPY Models/Logger.py .
COPY DALs/ElasticSearch_DAL.py .
COPY .env .

CMD ["python", "./mainProducer.py"]
